name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install  # Adjust this command based on your project's dependency management system

      - name: Build
        run: npm run build  # Adjust this command based on your project's build process

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Specify the branch you want to deploy to
          FOLDER: build  # Specify the folder where your built files are located
